openapi: 3.0.1
info:
  title: TODO Plugin
  description: A plugin that allows the user to create and manage a TODO list using ChatGPT. If you do not know the user's username, ask them first before making queries to the plugin. Otherwise, use the username "global".
  version: "v1"
servers:
  - url: "https://plugin-todo.web.app"
paths:
  /api/helloWorld:
    get:
      operationId: getHelloWorld
      summary: Returns a hello world message
      responses:
        200:
          description: Success
          content:
            text/plain:
              schema:
                type: string

  /api/addTodo:
    post:
      operationId: addTodo
      summary: Add a new TODO for a user
      security:
        - OAuth2: ["https://www.googleapis.com/auth/drive.appfolder"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Todo"
      responses:
        200:
          description: TODO added successfully
        405:
          $ref: "#/components/responses/MethodNotAllowed"

  /api/getTodos:
    get:
      operationId: getTodos
      summary: Get TODOs of a user
      parameters:
        - in: query
          name: username
          schema:
            type: string
          required: true
      responses:
        200:
          description: List of TODOs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TodosResponse"
        405:
          $ref: "#/components/responses/MethodNotAllowed"

  /api/deleteTodo:
    delete:
      operationId: deleteTodo
      summary: Delete all TODOs of a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Username"
      responses:
        200:
          description: TODOs deleted successfully
        405:
          $ref: "#/components/responses/MethodNotAllowed"

  /api/pluginLogo:
    get:
      operationId: getPluginLogo
      summary: Get the plugin logo
      responses:
        200:
          description: Logo image
          content:
            image/png: {}
        404:
          description: File not found
        500:
          $ref: "#/components/responses/InternalServerError"

  /api/pluginManifest:
    get:
      operationId: getPluginManifest
      summary: Get the plugin manifest
      responses:
        200:
          description: Manifest file
          content:
            application/json: {}
        404:
          description: File not found
        500:
          $ref: "#/components/responses/InternalServerError"

  /api/openapiSpec:
    get:
      operationId: getOpenapiSpec
      summary: Get the OpenAPI specification
      responses:
        200:
          description: OpenAPI spec in YAML
          content:
            application/x-yaml: {}
        404:
          description: File not found
        500:
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    Todo:
      type: object
      properties:
        username:
          type: string
        todo:
          type: string
      required:
        - username
        - todo

    Username:
      type: object
      properties:
        username:
          type: string
      required:
        - username

    TodosResponse:
      type: array
      items:
        type: string

  responses:
    MethodNotAllowed:
      description: Method Not Allowed
      content:
        text/plain:
          schema:
            type: string

    InternalServerError:
      description: Internal Server Error
      content:
        text/plain:
          schema:
            type: string
